version: '3.8'

services:
  db_farmacia:
    image: mysql:8.0
    container_name: mysql_farmacia
    environment:
      MYSQL_DATABASE: farmacia_db
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3307:3306" # Externo:Interno
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - farmacia_data:/var/lib/mysql
    networks:
      - farmacia_network

  backend:
    build: ./backend/farmacia-api
    container_name: api_farmacia
    ports:
      - "8081:8081"
    depends_on:
      db_farmacia:
        condition: service_healthy
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_farmacia:3306/farmacia_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MAIL_PASSWORD=yilb ezld rfdm pprl 
    networks:
      - farmacia_network

  gateway:
    build: "./Api Gateway/gateway-service"
    container_name: gateway_farmacia
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - SERVER_PORT=8080
      - BACKEND_URI=http://backend:8081
    networks:
      - farmacia_network

  #frontend:
  #  build: ./frontend/Farmacia-Interna
  #  container_name: web_farmacia
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - gateway
  #  networks:
  #    - farmacia_network

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --url http://gateway:8080
    depends_on:
      - gateway
    networks:
      - farmacia_network

volumes:
  farmacia_data:

networks:
  farmacia_network:
    driver: bridge