services:
  db_farmacia:
    image: mysql:8.0
    container_name: mysql_farmacia
    environment:
      MYSQL_DATABASE: farmacia_db
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
    volumes:
      - farmacia_data:/var/lib/mysql

  backend:
    build: ./backend/farmacia-api
    container_name: api_farmacia
    ports:
      - "8081:8081"
    depends_on:
      db_farmacia:
        condition: service_healthy
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_farmacia:3306/farmacia_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  gateway:
    build: "./Api Gateway/gateway-service"
    container_name: gateway_farmacia
    ports:
      - "8080:8080"
    depends_on:
      - backend

  frontend:
    build: ./frontend/Farmacia-Interna
    container_name: web_farmacia
    ports:
      - "80:80"
    depends_on:
      - gateway

volumes:
  farmacia_data: